{
 "title": "Elys Network",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Load (1-5-15)",
   "type": "timeseries",
   "description": "The CPU load should not exceed the number of cores available. \nE.g., if your server has 4 vCPU, the the load average should stay below 4, otherwise it means the server lacks computing power.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "Load Average 1" },
    { "expr": "node_load5", "legendFormat": "Load Average 5" },
    { "expr": "node_load15", "legendFormat": "Load Average 15" }
   ]
  },
  {
   "title": "Available Memory & Swap",
   "type": "timeseries",
   "description": "Green line = remaining free RAM\nOrange line = remaining free swap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes/1073741824"
    },
    {
     "expr": "node_memory_SwapFree_bytes/1073741824"
    }
   ]
  },
  {
   "title": "Disk Space | Root",
   "type": "timeseries",
   "description": "Available disk space in Gb on the root partition",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\"}/1073741824"
    }
   ]
  },
  {
   "title": "IOwait",
   "type": "timeseries",
   "description": "% of time that the CPU was idle, waiting for write or read operations to complete.\nIf it is high, it usually indicates that the disk is not fast enough.\nIt should be a close to 0 as possible",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode=\"iowait\"}[5m])*100"
    }
   ]
  },
  {
   "title": "Disk Space | Volume",
   "type": "timeseries",
   "description": "The available disk space on an external disk.\nUpdate the target (default /dev/sdb/) as required, or delete this panel if there is no additional volume to monitor.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/sdb\"}/1073741824"
    }
   ]
  },
  { "title": "ELYS NETWORK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Up ",
   "type": "timeseries",
   "description": "1 when the node is running, 0 when it is down",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "up{instance=\"localhost:26660\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Missed Blocks",
   "type": "timeseries",
   "description": "The number of missed blocks (= not signed) since the last restart of the node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "cometbft_consensus_validator_missed_blocks{job=\"datasource\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Height  ",
   "type": "timeseries",
   "description": "Current height of the blockchain. \nIt should constantly increase, if the line is flat at some point it means the node is hung or the chain has halted.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cometbft_consensus_height{instance=\"localhost:26660\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Total Voting Power ",
   "type": "timeseries",
   "description": "Variations of the voting power over time. \nIt displays the gains and losses in delegations.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cometbft_consensus_validator_power{instance=\"localhost:26660\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  }
 ]
}